export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const SET_TASK_EDIT_ID = 'SET_TASK_EDIT_ID';
export const SHOW_PRELOADER = 'SHOW_PRELOADER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const TRIGGER_SNACKBAR = 'TRIGGER_SNACKBAR';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const CREATE_TASKS_START = 'CREATE_TASKS_START';
export const CREATE_TASKS_SUCCESS = 'CREATE_TASKS_SUCCESS';
export const CREATE_TASKS_FAILURE = 'CREATE_TASKS_FAILURE';


export const EDIT_TASK_START = 'EDIT_TASK_START';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

export const SET_CURRENT_SORTING = 'SET_CURRENT_SORTING';
